//! Reads the pilots' faces out of the payload (`pilot_faces`): for each pilot of `pilot_stats`, the
//! string that names it, its side, and the films of its face the radio's window plays as it speaks
//! (`pilots.Face`).
//!
//! The table holds a record for each pilot `pilots.Table` holds, which `object_set_pilot` points an
//! object at by the pilot's number, as it does the pilot's record of `pilot_stats`.

const std = @import("std");
const Io = std.Io;

const openreliant = @import("openreliant");
const pilots = openreliant.engine.game.pilots;
const Face = pilots.Face;

const image = @import("image.zig");
const testing = @import("testing.zig");
const zig_text = @import("zig_text.zig");

/// `pilot_faces`, which `object_set_pilot` (`0x0049CCE0`) and `radio_say_pilot` (`0x00456250`)
/// index.
pub const table: u32 = 0x005048D8;

pub const Error = image.Error || error{NoFilm};

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)![]const Face {
    const records = try reader.records(Face.Record, table, pilots.Table.count);
    const faces = try arena.alloc(Face, records.len);
    for (faces, records) |*face, record| {
        var films: [Face.heads][]const u8 = undefined;
        for (&films, record.films) |*film, name| {
            film.* = try reader.string(@intFromEnum(name));
            if (film.len == 0) return error.NoFilm;
        }
        face.* = .{ .name = record.name, .side = record.side, .films = films };
    }
    return faces;
}

/// Writes `pilots/faces.zig`.
pub fn emit(w: *Io.Writer, faces: []const Face) Io.Writer.Error!void {
    try w.print(
        \\//! The pilots' faces: for each pilot of `pilot_stats`, the language string that names it, its
        \\//! side, and the films of its face, one for each way it moves as it speaks.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's `pilot_faces` at
        \\//! 0x{X:0>8}, {d} pilots. Do not edit by hand; run `make face-tables`.
        \\
        \\const pilots = @import("../pilots.zig");
        \\
        \\/// Every pilot's face, by the pilot's number.
        \\pub const faces = [{d}]pilots.Face{{
        \\
    , .{ table, faces.len, faces.len });
    for (faces, 0..) |face, index| {
        try w.print("    // {d}\n    .{{ .name = {d}, .side = ", .{ index, face.name });
        try zig_text.enumValue(w, face.side);
        try w.writeAll(", .films = .{ ");
        for (face.films, 0..) |film, head| {
            try w.print("{s}\"{f}\"", .{ if (head == 0) "" else ", ", std.zig.fmtString(film) });
        }
        try w.writeAll(" } },\n");
    }
    try w.writeAll(
        \\};
        \\
    );
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const size = pilots.Table.count * @sizeOf(Face.Record);
    const bytes = try allocator.alloc(u8, size + 0x40);
    defer allocator.free(bytes);
    @memset(bytes, 0);
    const region: testing.Region = .{ .va = table, .bytes = bytes };
    // Every pilot names the same four films, which lie after the table; the second is hostile.
    const names = table + size;
    region.putString(names, "45Tigers_Plt");
    region.putString(names + 0x10, "45Tigers_Plt_L");
    region.putString(names + 0x20, "45Tigers_Plt_D");
    for (0..pilots.Table.count) |pilot| {
        region.putRecord(table + @as(u32, @intCast(pilot)) * @sizeOf(Face.Record), Face.Record{
            .name = @intCast(0x20 + pilot),
            ._unknown_02 = 0x53,
            .side = if (pilot == 1) .hostile else .friendly,
            ._unknown_06 = 5,
            .films = .{ @enumFromInt(names), @enumFromInt(names + 0x10), @enumFromInt(names), @enumFromInt(names + 0x20) },
        });
    }

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const faces = try read(arena, payload);
    try std.testing.expectEqual(pilots.Table.count, faces.len);
    try std.testing.expectEqual(0x21, faces[1].name);
    try std.testing.expectEqual(.hostile, faces[1].side);
    try std.testing.expectEqualStrings("45Tigers_Plt_D", faces[5].films[3]);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, faces);
    try testing.expectZig(out.written());

    // A pilot without a film is not a table this reader knows.
    region.putWord(table + @offsetOf(Face.Record, "films"), 0);
    const broken = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, broken);
    try std.testing.expectError(error.NoFilm, read(arena, broken));
}
