//! Reads the speech codec's tables out of the payload: the levels its reflection coefficients are
//! quantized to, and the code its pulses are read with (`engine/game/voice.zig`).
//!
//! The levels are 64 floats. The code is a table of 256 symbols for each of its two contexts,
//! indexed by the stream's next eight bits, and a record for each symbol: the context the next
//! symbol is read in, the symbol's length in bits, and its value. The records run to the highest
//! symbol the tables name.

const std = @import("std");
const Io = std.Io;
const assert = std.debug.assert;

const image = @import("image.zig");
const testing = @import("testing.zig");

/// The levels (`0x005090E4`), the two contexts' symbols (`0x005091E4`) and the records
/// (`0x005093E8`), which the codec's frame decoder (`0x004A73B0`) and its pulse reader
/// (`0x004A76A0`) read.
pub const levels_table: u32 = 0x005090E4;
pub const symbols_table: u32 = 0x005091E4;
pub const records_table: u32 = 0x005093E8;

pub const level_count = 64;
pub const contexts = 2;
pub const symbols_per_context = 256;

/// A record as the payload lays it out.
pub const Record = extern struct {
    next: u32,
    bits: u32,
    value: f32,

    comptime {
        assert(@sizeOf(Record) == 12);
    }
};

pub const Tables = struct {
    levels: [level_count]f32,
    symbols: [contexts][symbols_per_context]u8,
    records: []const Record,
};

pub const Error = image.Error || error{BadRecord};

pub fn read(arena: std.mem.Allocator, reader: image.Reader) (Error || std.mem.Allocator.Error)!Tables {
    var tables: Tables = undefined;
    for (&tables.levels, 0..) |*level, index| level.* = try reader.recordAt(f32, levels_table, index);
    const symbols = try reader.slice(symbols_table, contexts * symbols_per_context);
    var highest: u8 = 0;
    for (&tables.symbols, 0..) |*context, index| {
        @memcpy(context, symbols[index * symbols_per_context ..][0..symbols_per_context]);
        for (context) |symbol| highest = @max(highest, symbol);
    }
    const records = try arena.alloc(Record, @as(usize, highest) + 1);
    for (records, 0..) |*record, index| {
        record.* = try reader.recordAt(Record, records_table, index);
        if (record.next >= contexts or record.bits == 0 or record.bits > 8) return error.BadRecord;
    }
    tables.records = records;
    return tables;
}

/// Writes `voice/tables.zig`.
pub fn emit(w: *Io.Writer, tables: Tables) Io.Writer.Error!void {
    try w.print(
        \\//! The speech codec's tables: the levels its reflection coefficients are quantized to, and the
        \\//! code its pulses are read with.
        \\//!
        \\//! Generated by `src/tools/tablegen` from the payload executable's tables at 0x{X:0>8},
        \\//! 0x{X:0>8} and 0x{X:0>8}. Do not edit by hand; run `make speech-tables`.
        \\
        \\/// The levels a reflection coefficient is quantized to.
        \\pub const levels = [{d}]f32{{
        \\
    , .{ levels_table, symbols_table, records_table, level_count });
    for (tables.levels) |level| try w.print("    {d},\n", .{level});
    try w.print(
        \\}};
        \\
        \\/// For each of the code's two contexts, the symbol the stream's next eight bits begin with.
        \\pub const symbols = [{d}][{d}]u8{{
        \\
    , .{ contexts, symbols_per_context });
    for (tables.symbols) |context| {
        try w.writeAll("    .{\n");
        for (context, 0..) |symbol, index| {
            try w.print("{s}{d},", .{ if (index % 16 == 0) "        " else " ", symbol });
            if (index % 16 == 15) try w.writeAll("\n");
        }
        try w.writeAll("    },\n");
    }
    try w.writeAll(
        \\};
        \\
        \\/// A symbol of the code: the context the next symbol is read in, its length in bits, and its
        \\/// value.
        \\pub const Symbol = struct {
        \\    next: u1,
        \\    bits: u4,
        \\    value: f32,
        \\};
        \\
        \\/// Every symbol the contexts name.
        \\pub const records = [_]Symbol{
        \\
    );
    for (tables.records, 0..) |record, index| {
        try w.print("    .{{ .next = {d}, .bits = {d}, .value = {d} }}, // {d}\n", .{ record.next, record.bits, record.value, index });
    }
    try w.writeAll(
        \\};
        \\
    );
}

test read {
    const allocator = std.testing.allocator;
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const bytes = try allocator.alloc(u8, 0x400);
    defer allocator.free(bytes);
    @memset(bytes, 0);
    const region: testing.Region = .{ .va = levels_table, .bytes = bytes };
    for (0..level_count) |index| region.putRecord(levels_table + 4 * @as(u32, @intCast(index)), @as(f32, @floatFromInt(index)) / 64);
    // The second context's last symbol is the highest, 2, so there are three records.
    region.put(symbols_table + symbols_per_context * 2 - 1, &.{2});
    region.putRecord(records_table, Record{ .next = 1, .bits = 8, .value = 0 });
    region.putRecord(records_table + 12, Record{ .next = 0, .bits = 2, .value = -1 });
    region.putRecord(records_table + 24, Record{ .next = 1, .bits = 4, .value = 2 });

    const payload = try testing.reader(allocator, &.{region});
    defer testing.freeReader(allocator, payload);
    const tables = try read(arena, payload);
    try std.testing.expectEqual(0.5, tables.levels[32]);
    try std.testing.expectEqual(2, tables.symbols[1][255]);
    try std.testing.expectEqual(3, tables.records.len);
    try std.testing.expectEqual(-1, tables.records[1].value);

    var out: Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    try emit(&out.writer, tables);
    try testing.expectZig(out.written());
}
